version: "3.8"

services:
  app:
    container_name: docker-react-c
    image: docker-react-i
    build:
      context: .
    ports:
      - 443:80
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
