name: CI/CD  

on:  
  push:  
    branches:  
      - main  # Replace 'main' with your primary branch name  
  pull_request:  
    branches:  
      - main  # Replace 'main' with your primary branch name  

jobs:  
  build-and-test:  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test

    - name: Build
      run: npm run build

  Deploy:  
    needs: build-and-test  # This ensures that deploy job runs only if build job succeeds  
    name: deploy  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  
      - name: Connect  
        uses: appleboy/ssh-action@master  
        with:  
          username: ${{ secrets.USERNAME }}  
          password: ${{ secrets.PASSWORD }}  
          host: ${{ secrets.HOST }}  
          port: ${{ secrets.PORT }}  
          script: |  
            cd ${{ secrets.PATH }}  
            docker compose stop  
            git pull  
            docker compose restart
