# This is a basic workflow to help you get started with Actions
name: CI-CD

on:
  push:
    branches: [main]


jobs:
  build_test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install --force

      # build and test the apps
      - name: build
        run: |
          npm run build
          npm test
