name: React CI with Docker

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t your-image-name .

    - name: Run Docker container
      run: docker run -d -p 3000:3000 your-image-name
