# This is a basic workflow to help you get started with Actions
name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

    


jobs:
  build_test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
    
      - name: setup node
        uses: actions/setup-node@master

      - name : docker-compose up
        run: docker compose up --bupld
        
      # install applicaion dependencies
      - name: Install dependencies
        run: |
          docker exec -it docker-react-c bash "npm install --force"

      # build and test the apps
      - name: build
        run: |
          docker exec -it docker-react-c bash "npm run build"
          docker exec -it docker-react-c bash "npm test"
